version: '3'

services:
    urlmeta-sanic:
        build:
            context: app
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        command: python /app/app_sanic.py
        volumes:
            - ./app:/app

    urlmeta-japronto:
        build:
            context: app
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        command: python /app/app_japronto.py
        volumes:
            - ./app:/app
